services:
  chat:
    image: ghcr.io/ayaka-notes/overleaf-pro/dev:chat

  clsi:
    image: ghcr.io/ayaka-notes/overleaf-pro/dev:clsi

  contacts:
    image: ghcr.io/ayaka-notes/overleaf-pro/dev:contacts

  docstore:
    image: ghcr.io/ayaka-notes/overleaf-pro/dev:docstore

  document-updater:
    image: ghcr.io/ayaka-notes/overleaf-pro/dev:document-updater

  filestore:
    image: ghcr.io/ayaka-notes/overleaf-pro/dev:filestore

  history-v1:
    image: ghcr.io/ayaka-notes/overleaf-pro/dev:history-v1

  notifications:
    image: ghcr.io/ayaka-notes/overleaf-pro/dev:notifications

  project-history:
    image: ghcr.io/ayaka-notes/overleaf-pro/dev:project-history

  real-time:
    image: ghcr.io/ayaka-notes/overleaf-pro/dev:real-time

  spelling:
    image: ghcr.io/ayaka-notes/overleaf-pro/dev:spelling

  web:
    image: ghcr.io/ayaka-notes/overleaf-pro/dev:web

  webpack:
    image: ghcr.io/ayaka-notes/overleaf-pro/dev:webpack
